### ISSUE TITLE
SA23 contributor headshots

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#41]
Contributor bios added to dev.soundamerican.org. We'll need headshots at some point, I suppose.

**Comment by jasloe** [comment]
Refer to #23 for file size guidelines for headshots.

**Comment by natewooley** [comment]
Yeah, had problems getting headshots that would upload, either because of parameters or something was wrong with the module. I can stay on this, but was wasting too much time and decided to keep going with the bios since that wasn't giving me problems. 

I am in the office this morning and early afternoon and then need to get home to prepare for my early flight tomorrow. Should we meet when you get in so I can prepare a punchlist for the time I'm in Oregon?

**Comment by jasloe** [comment]
Oops, I just tested that. It's a file permissions issue. I'll loosen those up this afternoon.

I'm a little tied up this morning though will be in the gallery by 1:30 at the latest. Are you available at that time? If we could meet for 30 to 45 minutes, that'd be great

**Comment by natewooley** [comment]
Cool...thanks. I figured the size thing wasn't that prohibited. 

I will need to split as early as possible as i need to get some house stuff fixed before I leave tomorrow, but if we do it right at 1:30 I'm good. It would be helpful for me to have a list of things to work on while I'm gone. Just talked to Mike Dyer and he says we should have first pass of SA23 by 12/28

**Comment by jasloe** [comment]
Closing this issue in favor of #32. See notes there.
